root = "."
tmp_dir = "tmp"

[build]
cmd = "dlv debug --headless --listen=:2345 --api-version=2 --accept-multiclient"

bin = "tmp/main"
full_bin = true
exclude_dir = ["tmp", "vendor"]

[log]
time = true
